# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

    # Use the base box for speed
    config.vm.box = "../1_BASE_BOX/base_agent.box"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    config.vm.network "private_network", ip: "192.168.231.44"


    # Share the agent installation file with the VM
    config.vm.synced_folder "./ucd_config", "/ucd_config"

 
    config.vm.provider "virtualbox" do |vb|
        # Customize the amount of memory on the VM:
        vb.memory = "4096"
    end
 

    # Provision the Agent
    config.vm.provision "shell", inline: <<-SHELL

        #GET AGENT
        wget http://192.168.232.77:8080/tools/ibm-ucd-agent.zip
        unzip ibm-ucd-agent.zip
        cd ibm-ucd-agent-install/
      

        #INSTALL UCD AGENT
        sudo ./install-agent-from-file.sh /ucd_config/agent.install.properties

        #START UCD AGENT
        sudo /opt/ibm-ucd/agent/bin/agent start

        #DOCKER UI
        docker run -d -p 9000:9000 --name "DOCKER_UI" --privileged -v /var/run/docker.sock:/var/run/docker.sock dockerui/dockerui

        #RANCHER
        #sudo docker run -d --name RANCHER_SERVER --restart=always -p 9003:8080 rancher/server


  SHELL
end
