# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
    # Use the base box for speed
    config.vm.box = "../1_BASE_BOX/base_agent.box"
   
    config.vm.provider "virtualbox" do |vb|
        # Customize the amount of memory on the VM:
        vb.memory = "512"
    end
    
    (1..3).each do |i|    
        config.vm.define "agent#{i}" do |agent|
            # Create a private network, which allows host-only access to the machine using a specific IP.
            agent.vm.network "private_network", ip: "192.168.231.4#{i}"    #Creates agents in the 192.168.231.4x subnet
            
            # Share the agent installation file with the VM
            agent.vm.synced_folder "./ucd_config", "/ucd_config"
            agent.vm.provision :shell, :path => "./ucd_config/install.sh", :args => "'#{i}'"
        end
    end
end

